services:
  marzban-node:
    build: .
    # image: gozargah/marzban-node:latest
    restart: always
    network_mode: host

    environment:
      SSL_CERT_FILE: "./cert/ssl_cert.pem"
      SSL_KEY_FILE: "./cert/ssl_key.pem"
      # SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"

    volumes:
      - ./cert:/var/lib/marzban-node
